# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGNjODhlNTQ1N2Y2ZWQyYTNkNjQxMzM1NGMyZDVkZmNhYTcyZDhmMWEyZmU5YzY4ZThjYjBhYmZlZTdhNTNiZTVjZDM5OGU0MTM3ZTFjZjM0MjlhNWMxYTg3ZTAxZDY2YThkNGViMzc3YmZlMTM5MzQ0MjViYTkxY2YxOTc0YjQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
